### PR TITLE
Issue #7: skip validation of target

### PR DESCRIPTION
**Pull request by krulls**
see issue #7

### CODE REVIEW

**Comment by krulls** [comment]
@jbronn : Hello jbronn, could you possibly review or rate this pull request?

**Comment by krulls** [comment]
@jamesob : How can this review process be accelerated?

**Comment by jonemo** [comment]
Sorry for the delay @krulls, I'll take this one to get this merged asap 

You make a good point in #7, Windows shortcuts can be paths, URLs and "shell objects" and this code only accounts for the first. I just spend a little time investigating whether there is a good way of validating this argument while allowing for every use case and couldn't think of anything short of writing a (probably complex and fragile) regex. 

The only suggestion I have is that as a basic form of validation we could do [`validate_string($target)`](https://github.com/puppetlabs/puppetlabs-stdlib#validate_string). Any thoughts on that? Lmk, I'm ok to merge this with or without.

**Comment by krulls** [comment]
It would probably be kind of perfect to validate a correct targetPath (like [here](http://snipplr.com/view/6889/regular-expressions-for-uri-validationparsing/)) but I assume it is sufficient to validate for a string. Powershell should kick in if something is wrong with this argument.

**Comment by jonemo** [comment]
Thanks @krulls! Merging and tagging new version now.

**Pull request merged**
